GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQnJhZHkiLCJpYXQiOjE2MTI1ODYyNjR9.Fvw7urIL6wxAw8FWDvh4hMwv7NzxDCwYobcckVeqWNo

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Brady"
}